//! Importing already-installed instances from other launchers: PrismLauncher
//! (also PolyMC/MultiMC), the CurseForge app, and the Modrinth App.
//!
//! Detection reads each launcher's per-instance metadata to recover the
//! Minecraft version + loader; importing copies the instance's game files
//! (mods, config, saves, …) into a fresh Mako instance. Regenerable/heavy
//! folders (versions, libraries, assets, …) are skipped — Lyceris re-provisions
//! them on first launch.

use std::io::{Cursor, Read, Write};
use std::path::{Component, Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::commands::instances;
use crate::models::{Instance, Loader};
use crate::{paths, store};

#[derive(Serialize, Clone)]
pub struct ExternalInstance {
    /// "prism" | "curseforge" | "modrinth"
    pub launcher: String,
    pub name: String,
    /// Source instance root (for display).
    pub path: String,
    /// Folder holding mods/config/saves to copy.
    pub game_dir: String,
    pub mc_version: Option<String>,
    /// "vanilla" | "fabric" | "quilt" | "forge" | "neoforge"
    pub loader: Option<String>,
    pub loader_version: Option<String>,
}

/// Scans known launcher data directories for importable instances.
#[tauri::command]
pub fn detect_external_instances() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    out.extend(scan_prism());
    out.extend(scan_curseforge());
    out.extend(scan_modrinth());
    out
}

/// Creates a new Mako instance from a detected external one, copying its files.
#[tauri::command]
pub fn import_external_instance(
    name: String,
    game_dir: String,
    mc_version: String,
    loader: Option<String>,
    loader_version: Option<String>,
) -> Result<Instance, String> {
    if mc_version.trim().is_empty() {
        return Err("could not determine the Minecraft version of this instance".into());
    }
    let src = PathBuf::from(&game_dir);
    if !src.is_dir() {
        return Err("source game directory not found".into());
    }

    let lver = loader_version.filter(|s| !s.trim().is_empty());
    let loader_enum = build_loader(loader.as_deref(), lver);
    let instance = instances::create_instance(name, mc_version, loader_enum, None, None)?;

    let dst = paths::instance_game_dir(&instance.id);
    if let Err(e) = copy_game_dir(&src, &dst) {
        // Roll back the half-made instance so a failed import leaves nothing.
        let _ = std::fs::remove_dir_all(paths::instance_dir(&instance.id));
        return Err(e);
    }
    Ok(instance)
}

// ---------- export / backup ----------

#[derive(Serialize, Deserialize)]
struct BackupManifest {
    /// Format marker so import can recognise a Mako backup.
    format: String,
    version: u32,
    /// The full instance config (its id is replaced on restore).
    instance: Instance,
}

const BACKUP_FORMAT: &str = "mako-instance-backup";
pub const BACKUP_MANIFEST: &str = "mako-instance.json";

/// A top-level game-dir entry, for the export selection UI.
#[derive(Serialize)]
pub struct InstanceEntry {
    name: String,
    is_dir: bool,
    size: u64,
    /// Whether it should be checked by default (e.g. mods yes, saves no).
    recommended: bool,
}

// Never offered for export (regenerated by the engine / pure noise).
const NEVER: &[&str] = &[
    "versions", "libraries", "assets", "bin", "natives", "logs", ".cache",
    ".fabric", ".quilt", ".mixin.out", "asm",
];
// Offered but unchecked by default (personal/heavy, not part of a pack).
const NOT_RECOMMENDED: &[&str] = &["saves", "screenshots", "crash-reports", "backups"];

/// Lists the top-level entries of an instance's game dir so the export dialog can
/// let the user choose what to include.
#[tauri::command]
pub fn list_instance_entries(id: String) -> Result<Vec<InstanceEntry>, String> {
    let game_dir = paths::instance_game_dir(&id);
    let mut out = Vec::new();
    let entries = std::fs::read_dir(&game_dir).map_err(|e| format!("read game dir: {e}"))?;
    for e in entries.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        let lower = name.to_lowercase();
        if NEVER.contains(&lower.as_str()) {
            continue;
        }
        let path = e.path();
        let is_dir = path.is_dir();
        let size = if is_dir { dir_size(&path) } else { e.metadata().map(|m| m.len()).unwrap_or(0) };
        out.push(InstanceEntry {
            name,
            is_dir,
            size,
            recommended: !NOT_RECOMMENDED.contains(&lower.as_str()),
        });
    }
    // Folders first, then alphabetical.
    out.sort_by(|a, b| b.is_dir.cmp(&a.is_dir).then(a.name.to_lowercase().cmp(&b.name.to_lowercase())));
    Ok(out)
}

fn dir_size(p: &Path) -> u64 {
    let mut total = 0;
    if let Ok(entries) = std::fs::read_dir(p) {
        for e in entries.flatten() {
            let path = e.path();
            if path.is_dir() {
                total += dir_size(&path);
            } else {
                total += e.metadata().map(|m| m.len()).unwrap_or(0);
            }
        }
    }
    total
}

/// Exports an instance to a self-contained `.zip` backup: its config (settings,
/// loader, version), icon, and the selected game-dir entries. Restorable via the
/// import file flow. `include` is the set of top-level entries to bundle.
#[tauri::command]
pub fn export_instance(id: String, dest: String, include: Vec<String>) -> Result<(), String> {
    let instance: Instance =
        store::read_json(&paths::instance_config_file(&id))?.ok_or("instance not found")?;
    let game_dir = paths::instance_game_dir(&id);
    let include: std::collections::HashSet<String> = include.into_iter().collect();

    let file = std::fs::File::create(&dest).map_err(|e| format!("create {dest}: {e}"))?;
    let mut zip = zip::ZipWriter::new(file);
    let opts = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);

    // manifest
    let manifest = BackupManifest { format: BACKUP_FORMAT.into(), version: 1, instance };
    let manifest_json = serde_json::to_vec_pretty(&manifest).map_err(|e| e.to_string())?;
    zip.start_file(BACKUP_MANIFEST, opts).map_err(|e| e.to_string())?;
    zip.write_all(&manifest_json).map_err(|e| e.to_string())?;

    // icon
    let icon = paths::instance_icon_file(&id);
    if let Ok(bytes) = std::fs::read(&icon) {
        zip.start_file("icon.png", opts).map_err(|e| e.to_string())?;
        zip.write_all(&bytes).map_err(|e| e.to_string())?;
    }

    // selected game files under minecraft/
    let entries = std::fs::read_dir(&game_dir).map_err(|e| format!("read game dir: {e}"))?;
    for e in entries.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        if !include.contains(&name) {
            continue;
        }
        let path = e.path();
        let zpath = format!("minecraft/{name}");
        if path.is_dir() {
            add_dir_to_zip(&mut zip, &path, &zpath, opts)?;
        } else {
            let bytes = std::fs::read(&path).map_err(|e| e.to_string())?;
            zip.start_file(&zpath, opts).map_err(|e| e.to_string())?;
            zip.write_all(&bytes).map_err(|e| e.to_string())?;
        }
    }

    zip.finish().map_err(|e| e.to_string())?;
    Ok(())
}

fn add_dir_to_zip<W: Write + std::io::Seek>(
    zip: &mut zip::ZipWriter<W>,
    src: &Path,
    prefix: &str,
    opts: zip::write::SimpleFileOptions,
) -> Result<(), String> {
    let Ok(entries) = std::fs::read_dir(src) else { return Ok(()) };
    for entry in entries.flatten() {
        let name = entry.file_name();
        // Filter regenerable folders at the game-dir top level only.
        if prefix == "minecraft" && SKIP.contains(&name.to_string_lossy().to_lowercase().as_str()) {
            continue;
        }
        let path = entry.path();
        let zpath = format!("{prefix}/{}", name.to_string_lossy());
        if path.is_dir() {
            add_dir_to_zip(zip, &path, &zpath, opts)?;
        } else {
            let bytes = std::fs::read(&path).map_err(|e| e.to_string())?;
            zip.start_file(&zpath, opts).map_err(|e| e.to_string())?;
            zip.write_all(&bytes).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

/// True if `bytes` is a Mako instance backup zip.
pub fn is_backup_zip(bytes: &[u8]) -> bool {
    let Ok(mut archive) = zip::ZipArchive::new(Cursor::new(bytes)) else { return false };
    let found = archive.by_name(BACKUP_MANIFEST).is_ok();
    found
}

/// Restores an instance from a Mako backup zip into a brand-new instance.
pub fn restore_backup_from_bytes(bytes: &[u8]) -> Result<Instance, String> {
    let mut archive =
        zip::ZipArchive::new(Cursor::new(bytes)).map_err(|e| format!("open backup: {e}"))?;

    let manifest: BackupManifest = {
        let mut f = archive
            .by_name(BACKUP_MANIFEST)
            .map_err(|_| "not a Mako backup".to_string())?;
        let mut s = String::new();
        f.read_to_string(&mut s).map_err(|e| e.to_string())?;
        serde_json::from_str(&s).map_err(|e| format!("parse manifest: {e}"))?
    };
    let src = manifest.instance;

    let created = instances::create_instance(
        src.name.clone(),
        src.mc_version.clone(),
        src.loader.clone(),
        None,
        None,
    )?;
    let new_id = created.id.clone();

    // Restore all settings, but with a fresh id and reset runtime stats.
    let mut instance = Instance {
        id: new_id.clone(),
        created_at: created.created_at,
        last_played: None,
        playtime_seconds: 0,
        icon: None,
        ..src
    };

    let game_dir = paths::instance_game_dir(&new_id);
    for i in 0..archive.len() {
        let mut entry = archive.by_index(i).map_err(|e| e.to_string())?;
        if entry.is_dir() {
            continue;
        }
        let name = entry.name().to_string();
        if name == "icon.png" {
            let mut buf = Vec::new();
            if entry.read_to_end(&mut buf).is_ok()
                && std::fs::write(paths::instance_icon_file(&new_id), &buf).is_ok()
            {
                instance.icon = Some("icon.png".into());
            }
            continue;
        }
        if let Some(rel) = name.strip_prefix("minecraft/") {
            let dest = join_safe(&game_dir, rel)?;
            if let Some(p) = dest.parent() {
                std::fs::create_dir_all(p).map_err(|e| e.to_string())?;
            }
            let mut buf = Vec::new();
            entry.read_to_end(&mut buf).map_err(|e| e.to_string())?;
            std::fs::write(&dest, &buf).map_err(|e| e.to_string())?;
        }
    }

    store::write_json(&paths::instance_config_file(&new_id), &instance)?;
    Ok(instance)
}

/// Joins a relative archive path onto `base`, rejecting traversal outside it.
fn join_safe(base: &Path, rel: &str) -> Result<PathBuf, String> {
    let mut out = base.to_path_buf();
    for comp in Path::new(rel).components() {
        match comp {
            Component::Normal(c) => out.push(c),
            Component::CurDir => {}
            _ => return Err(format!("unsafe path in backup: {rel}")),
        }
    }
    Ok(out)
}

fn build_loader(loader: Option<&str>, version: Option<String>) -> Loader {
    match loader.unwrap_or("vanilla") {
        "fabric" => Loader::Fabric(version.unwrap_or_default()),
        "quilt" => Loader::Quilt(version.unwrap_or_default()),
        "forge" => Loader::Forge(version.unwrap_or_default()),
        "neoforge" => Loader::NeoForge(version.unwrap_or_default()),
        _ => Loader::Vanilla,
    }
}

// ---------- copying ----------

// Top-level entries that are regenerated by the engine; never worth copying.
const SKIP: &[&str] = &[
    "versions", "libraries", "assets", "bin", "natives", "logs", ".cache",
    ".fabric", ".quilt", ".mixin.out", "asm", "patchouli_books",
];

fn copy_game_dir(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| format!("create dest: {e}"))?;
    for entry in std::fs::read_dir(src).map_err(|e| format!("read source: {e}"))?.flatten() {
        let name = entry.file_name();
        let lower = name.to_string_lossy().to_lowercase();
        if SKIP.contains(&lower.as_str()) {
            continue;
        }
        let from = entry.path();
        let to = dst.join(&name);
        if from.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            std::fs::copy(&from, &to).map_err(|e| format!("copy {}: {e}", from.display()))?;
        }
    }
    Ok(())
}

fn copy_dir_all(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| e.to_string())?;
    for entry in std::fs::read_dir(src).map_err(|e| e.to_string())?.flatten() {
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            std::fs::copy(&from, &to).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

// ---------- PrismLauncher / PolyMC / MultiMC ----------

fn scan_prism() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    let Some(data) = dirs::data_dir() else { return out };
    for app in ["PrismLauncher", "PolyMC", "MultiMC"] {
        let root = data.join(app).join("instances");
        let Ok(entries) = std::fs::read_dir(&root) else { continue };
        for e in entries.flatten() {
            let dir = e.path();
            let pack = dir.join("mmc-pack.json");
            if !dir.is_dir() || !pack.exists() {
                continue;
            }
            let game = if dir.join(".minecraft").is_dir() {
                dir.join(".minecraft")
            } else if dir.join("minecraft").is_dir() {
                dir.join("minecraft")
            } else {
                continue;
            };
            let name = read_cfg_value(&dir.join("instance.cfg"), "name")
                .unwrap_or_else(|| dir_name(&dir));
            let (mc, loader, lver) = parse_mmc_pack(&pack);
            out.push(ExternalInstance {
                launcher: "prism".into(),
                name,
                path: dir.to_string_lossy().into_owned(),
                game_dir: game.to_string_lossy().into_owned(),
                mc_version: mc,
                loader,
                loader_version: lver,
            });
        }
    }
    out
}

fn parse_mmc_pack(path: &Path) -> (Option<String>, Option<String>, Option<String>) {
    let Ok(raw) = std::fs::read_to_string(path) else { return (None, None, None) };
    let Ok(val) = serde_json::from_str::<serde_json::Value>(&raw) else { return (None, None, None) };
    let (mut mc, mut loader, mut lver) = (None, None, None);
    if let Some(comps) = val.get("components").and_then(|c| c.as_array()) {
        for c in comps {
            let uid = c.get("uid").and_then(|u| u.as_str()).unwrap_or("");
            let ver = c.get("version").and_then(|v| v.as_str()).map(String::from);
            match uid {
                "net.minecraft" => mc = ver,
                "net.fabricmc.fabric-loader" => { loader = Some("fabric".into()); lver = ver; }
                "org.quiltmc.quilt-loader" => { loader = Some("quilt".into()); lver = ver; }
                "net.minecraftforge" => { loader = Some("forge".into()); lver = ver; }
                "net.neoforged" => { loader = Some("neoforge".into()); lver = ver; }
                _ => {}
            }
        }
    }
    (mc, loader, lver)
}

/// Reads a `key=value` from a Prism `instance.cfg` (simple INI).
fn read_cfg_value(path: &Path, key: &str) -> Option<String> {
    let raw = std::fs::read_to_string(path).ok()?;
    for line in raw.lines() {
        if let Some((k, v)) = line.split_once('=') {
            if k.trim() == key {
                let v = v.trim();
                if !v.is_empty() {
                    return Some(v.to_string());
                }
            }
        }
    }
    None
}

// ---------- CurseForge app ----------

fn scan_curseforge() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    let mut roots = Vec::new();
    if let Some(d) = dirs::document_dir() {
        roots.push(d.join("Curseforge").join("Minecraft").join("Instances"));
    }
    if let Some(h) = dirs::home_dir() {
        roots.push(h.join("curseforge").join("minecraft").join("Instances"));
    }
    for root in roots {
        let Ok(entries) = std::fs::read_dir(&root) else { continue };
        for e in entries.flatten() {
            let dir = e.path();
            let meta = dir.join("minecraftinstance.json");
            if !dir.is_dir() || !meta.exists() {
                continue;
            }
            let (name, mc, loader, lver) = parse_cf(&meta);
            out.push(ExternalInstance {
                launcher: "curseforge".into(),
                name: name.unwrap_or_else(|| dir_name(&dir)),
                game_dir: dir.to_string_lossy().into_owned(),
                path: dir.to_string_lossy().into_owned(),
                mc_version: mc,
                loader,
                loader_version: lver,
            });
        }
    }
    out
}

fn parse_cf(path: &Path) -> (Option<String>, Option<String>, Option<String>, Option<String>) {
    let Ok(raw) = std::fs::read_to_string(path) else { return (None, None, None, None) };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&raw) else { return (None, None, None, None) };
    let name = v.get("name").and_then(|x| x.as_str()).map(String::from);
    let mc = v
        .get("gameVersion")
        .and_then(|x| x.as_str())
        .map(String::from)
        .or_else(|| {
            v.get("baseModLoader")
                .and_then(|b| b.get("minecraftVersion"))
                .and_then(|x| x.as_str())
                .map(String::from)
        });
    let (loader, lver) = v
        .get("baseModLoader")
        .and_then(|b| b.get("name"))
        .and_then(|x| x.as_str())
        .map(parse_cf_loader)
        .unwrap_or((None, None));
    (name, mc, loader, lver)
}

/// Parses CurseForge loader names like "forge-47.2.0" / "fabric-0.15.0".
fn parse_cf_loader(name: &str) -> (Option<String>, Option<String>) {
    let (kind, ver) = name.split_once('-').unwrap_or((name, ""));
    let loader = match kind.to_lowercase().as_str() {
        "forge" => "forge",
        "fabric" => "fabric",
        "neoforge" => "neoforge",
        "quilt" => "quilt",
        _ => return (None, None),
    };
    (Some(loader.into()), (!ver.is_empty()).then(|| ver.to_string()))
}

// ---------- Modrinth App ----------

fn scan_modrinth() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    let Some(data) = dirs::data_dir() else { return out };
    for app in ["ModrinthApp", "com.modrinth.theseus"] {
        let root = data.join(app).join("profiles");
        let Ok(entries) = std::fs::read_dir(&root) else { continue };
        for e in entries.flatten() {
            let dir = e.path();
            let meta = dir.join("profile.json");
            if !dir.is_dir() || !meta.exists() {
                continue;
            }
            let (name, mc, loader, lver) = parse_modrinth_profile(&meta, &dir_name(&dir));
            out.push(ExternalInstance {
                launcher: "modrinth".into(),
                name,
                game_dir: dir.to_string_lossy().into_owned(),
                path: dir.to_string_lossy().into_owned(),
                mc_version: mc,
                loader,
                loader_version: lver,
            });
        }
    }
    out
}

fn parse_modrinth_profile(
    path: &Path,
    fallback: &str,
) -> (String, Option<String>, Option<String>, Option<String>) {
    let Ok(raw) = std::fs::read_to_string(path) else { return (fallback.into(), None, None, None) };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&raw) else { return (fallback.into(), None, None, None) };
    // Newer profiles nest under "metadata"; older keep it flat.
    let meta = v.get("metadata").unwrap_or(&v);
    let name = meta.get("name").and_then(|x| x.as_str()).map(String::from).unwrap_or_else(|| fallback.into());
    let mc = meta.get("game_version").and_then(|x| x.as_str()).map(String::from);
    let loader = meta
        .get("loader")
        .and_then(|x| x.as_str())
        .map(|s| s.to_lowercase())
        .filter(|s| s != "vanilla");
    let lver = meta.get("loader_version").and_then(|lv| {
        lv.as_str()
            .map(String::from)
            .or_else(|| lv.get("id").and_then(|i| i.as_str()).map(String::from))
    });
    (name, mc, loader, lver)
}

fn dir_name(p: &Path) -> String {
    p.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default()
}
