//! Importing already-installed instances from other launchers: PrismLauncher
//! (also PolyMC/MultiMC), the CurseForge app, and the Modrinth App.
//!
//! Detection reads each launcher's per-instance metadata to recover the
//! Minecraft version + loader; importing copies the instance's game files
//! (mods, config, saves, …) into a fresh Mako instance. Regenerable/heavy
//! folders (versions, libraries, assets, …) are skipped — Lyceris re-provisions
//! them on first launch.

use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::commands::instances;
use crate::models::{Instance, Loader};
use crate::paths;

#[derive(Serialize, Clone)]
pub struct ExternalInstance {
    /// "prism" | "curseforge" | "modrinth"
    pub launcher: String,
    pub name: String,
    /// Source instance root (for display).
    pub path: String,
    /// Folder holding mods/config/saves to copy.
    pub game_dir: String,
    pub mc_version: Option<String>,
    /// "vanilla" | "fabric" | "quilt" | "forge" | "neoforge"
    pub loader: Option<String>,
    pub loader_version: Option<String>,
}

/// Scans known launcher data directories for importable instances.
#[tauri::command]
pub fn detect_external_instances() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    out.extend(scan_prism());
    out.extend(scan_curseforge());
    out.extend(scan_modrinth());
    out
}

/// Creates a new Mako instance from a detected external one, copying its files.
#[tauri::command]
pub fn import_external_instance(
    name: String,
    game_dir: String,
    mc_version: String,
    loader: Option<String>,
    loader_version: Option<String>,
) -> Result<Instance, String> {
    if mc_version.trim().is_empty() {
        return Err("could not determine the Minecraft version of this instance".into());
    }
    let src = PathBuf::from(&game_dir);
    if !src.is_dir() {
        return Err("source game directory not found".into());
    }

    let lver = loader_version.filter(|s| !s.trim().is_empty());
    let loader_enum = build_loader(loader.as_deref(), lver);
    let instance = instances::create_instance(name, mc_version, loader_enum, None, None)?;

    let dst = paths::instance_game_dir(&instance.id);
    if let Err(e) = copy_game_dir(&src, &dst) {
        // Roll back the half-made instance so a failed import leaves nothing.
        let _ = std::fs::remove_dir_all(paths::instance_dir(&instance.id));
        return Err(e);
    }
    Ok(instance)
}

fn build_loader(loader: Option<&str>, version: Option<String>) -> Loader {
    match loader.unwrap_or("vanilla") {
        "fabric" => Loader::Fabric(version.unwrap_or_default()),
        "quilt" => Loader::Quilt(version.unwrap_or_default()),
        "forge" => Loader::Forge(version.unwrap_or_default()),
        "neoforge" => Loader::NeoForge(version.unwrap_or_default()),
        _ => Loader::Vanilla,
    }
}

// ---------- copying ----------

// Top-level entries that are regenerated by the engine; never worth copying.
const SKIP: &[&str] = &[
    "versions", "libraries", "assets", "bin", "natives", "logs", ".cache",
    ".fabric", ".quilt", ".mixin.out", "asm", "patchouli_books",
];

fn copy_game_dir(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| format!("create dest: {e}"))?;
    for entry in std::fs::read_dir(src).map_err(|e| format!("read source: {e}"))?.flatten() {
        let name = entry.file_name();
        let lower = name.to_string_lossy().to_lowercase();
        if SKIP.contains(&lower.as_str()) {
            continue;
        }
        let from = entry.path();
        let to = dst.join(&name);
        if from.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            std::fs::copy(&from, &to).map_err(|e| format!("copy {}: {e}", from.display()))?;
        }
    }
    Ok(())
}

fn copy_dir_all(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| e.to_string())?;
    for entry in std::fs::read_dir(src).map_err(|e| e.to_string())?.flatten() {
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            std::fs::copy(&from, &to).map_err(|e| e.to_string())?;
        }
    }
    Ok(())
}

// ---------- PrismLauncher / PolyMC / MultiMC ----------

fn scan_prism() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    let Some(data) = dirs::data_dir() else { return out };
    for app in ["PrismLauncher", "PolyMC", "MultiMC"] {
        let root = data.join(app).join("instances");
        let Ok(entries) = std::fs::read_dir(&root) else { continue };
        for e in entries.flatten() {
            let dir = e.path();
            let pack = dir.join("mmc-pack.json");
            if !dir.is_dir() || !pack.exists() {
                continue;
            }
            let game = if dir.join(".minecraft").is_dir() {
                dir.join(".minecraft")
            } else if dir.join("minecraft").is_dir() {
                dir.join("minecraft")
            } else {
                continue;
            };
            let name = read_cfg_value(&dir.join("instance.cfg"), "name")
                .unwrap_or_else(|| dir_name(&dir));
            let (mc, loader, lver) = parse_mmc_pack(&pack);
            out.push(ExternalInstance {
                launcher: "prism".into(),
                name,
                path: dir.to_string_lossy().into_owned(),
                game_dir: game.to_string_lossy().into_owned(),
                mc_version: mc,
                loader,
                loader_version: lver,
            });
        }
    }
    out
}

fn parse_mmc_pack(path: &Path) -> (Option<String>, Option<String>, Option<String>) {
    let Ok(raw) = std::fs::read_to_string(path) else { return (None, None, None) };
    let Ok(val) = serde_json::from_str::<serde_json::Value>(&raw) else { return (None, None, None) };
    let (mut mc, mut loader, mut lver) = (None, None, None);
    if let Some(comps) = val.get("components").and_then(|c| c.as_array()) {
        for c in comps {
            let uid = c.get("uid").and_then(|u| u.as_str()).unwrap_or("");
            let ver = c.get("version").and_then(|v| v.as_str()).map(String::from);
            match uid {
                "net.minecraft" => mc = ver,
                "net.fabricmc.fabric-loader" => { loader = Some("fabric".into()); lver = ver; }
                "org.quiltmc.quilt-loader" => { loader = Some("quilt".into()); lver = ver; }
                "net.minecraftforge" => { loader = Some("forge".into()); lver = ver; }
                "net.neoforged" => { loader = Some("neoforge".into()); lver = ver; }
                _ => {}
            }
        }
    }
    (mc, loader, lver)
}

/// Reads a `key=value` from a Prism `instance.cfg` (simple INI).
fn read_cfg_value(path: &Path, key: &str) -> Option<String> {
    let raw = std::fs::read_to_string(path).ok()?;
    for line in raw.lines() {
        if let Some((k, v)) = line.split_once('=') {
            if k.trim() == key {
                let v = v.trim();
                if !v.is_empty() {
                    return Some(v.to_string());
                }
            }
        }
    }
    None
}

// ---------- CurseForge app ----------

fn scan_curseforge() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    let mut roots = Vec::new();
    if let Some(d) = dirs::document_dir() {
        roots.push(d.join("Curseforge").join("Minecraft").join("Instances"));
    }
    if let Some(h) = dirs::home_dir() {
        roots.push(h.join("curseforge").join("minecraft").join("Instances"));
    }
    for root in roots {
        let Ok(entries) = std::fs::read_dir(&root) else { continue };
        for e in entries.flatten() {
            let dir = e.path();
            let meta = dir.join("minecraftinstance.json");
            if !dir.is_dir() || !meta.exists() {
                continue;
            }
            let (name, mc, loader, lver) = parse_cf(&meta);
            out.push(ExternalInstance {
                launcher: "curseforge".into(),
                name: name.unwrap_or_else(|| dir_name(&dir)),
                game_dir: dir.to_string_lossy().into_owned(),
                path: dir.to_string_lossy().into_owned(),
                mc_version: mc,
                loader,
                loader_version: lver,
            });
        }
    }
    out
}

fn parse_cf(path: &Path) -> (Option<String>, Option<String>, Option<String>, Option<String>) {
    let Ok(raw) = std::fs::read_to_string(path) else { return (None, None, None, None) };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&raw) else { return (None, None, None, None) };
    let name = v.get("name").and_then(|x| x.as_str()).map(String::from);
    let mc = v
        .get("gameVersion")
        .and_then(|x| x.as_str())
        .map(String::from)
        .or_else(|| {
            v.get("baseModLoader")
                .and_then(|b| b.get("minecraftVersion"))
                .and_then(|x| x.as_str())
                .map(String::from)
        });
    let (loader, lver) = v
        .get("baseModLoader")
        .and_then(|b| b.get("name"))
        .and_then(|x| x.as_str())
        .map(parse_cf_loader)
        .unwrap_or((None, None));
    (name, mc, loader, lver)
}

/// Parses CurseForge loader names like "forge-47.2.0" / "fabric-0.15.0".
fn parse_cf_loader(name: &str) -> (Option<String>, Option<String>) {
    let (kind, ver) = name.split_once('-').unwrap_or((name, ""));
    let loader = match kind.to_lowercase().as_str() {
        "forge" => "forge",
        "fabric" => "fabric",
        "neoforge" => "neoforge",
        "quilt" => "quilt",
        _ => return (None, None),
    };
    (Some(loader.into()), (!ver.is_empty()).then(|| ver.to_string()))
}

// ---------- Modrinth App ----------

fn scan_modrinth() -> Vec<ExternalInstance> {
    let mut out = Vec::new();
    let Some(data) = dirs::data_dir() else { return out };
    for app in ["ModrinthApp", "com.modrinth.theseus"] {
        let root = data.join(app).join("profiles");
        let Ok(entries) = std::fs::read_dir(&root) else { continue };
        for e in entries.flatten() {
            let dir = e.path();
            let meta = dir.join("profile.json");
            if !dir.is_dir() || !meta.exists() {
                continue;
            }
            let (name, mc, loader, lver) = parse_modrinth_profile(&meta, &dir_name(&dir));
            out.push(ExternalInstance {
                launcher: "modrinth".into(),
                name,
                game_dir: dir.to_string_lossy().into_owned(),
                path: dir.to_string_lossy().into_owned(),
                mc_version: mc,
                loader,
                loader_version: lver,
            });
        }
    }
    out
}

fn parse_modrinth_profile(
    path: &Path,
    fallback: &str,
) -> (String, Option<String>, Option<String>, Option<String>) {
    let Ok(raw) = std::fs::read_to_string(path) else { return (fallback.into(), None, None, None) };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&raw) else { return (fallback.into(), None, None, None) };
    // Newer profiles nest under "metadata"; older keep it flat.
    let meta = v.get("metadata").unwrap_or(&v);
    let name = meta.get("name").and_then(|x| x.as_str()).map(String::from).unwrap_or_else(|| fallback.into());
    let mc = meta.get("game_version").and_then(|x| x.as_str()).map(String::from);
    let loader = meta
        .get("loader")
        .and_then(|x| x.as_str())
        .map(|s| s.to_lowercase())
        .filter(|s| s != "vanilla");
    let lver = meta.get("loader_version").and_then(|lv| {
        lv.as_str()
            .map(String::from)
            .or_else(|| lv.get("id").and_then(|i| i.as_str()).map(String::from))
    });
    (name, mc, loader, lver)
}

fn dir_name(p: &Path) -> String {
    p.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default()
}
